### ISSUE TITLE
Обсуждаем параметр PK

### ISSUE THREAD

**Issue by rianby64** [m3co/arca-dbbus#2]
`Create` использует

```json
{
  "ID": "--UUID4-value()--",
  "Method": "Insert",
  "Context": {
    "Source": "--Name-Table--"
  },
  "Params": {
    "Row": { ... }
  }
}
```

`Delete` использует

```json
{
  "ID": "--UUID4-value()--",
  "Method": "Delete",
  "Context": {
    "Source": "--Name-Table--"
  },
  "Params": {
    "Has": { ... }
  }
}
```

`Update` использует

```json
{
  "ID": "--UUID4-value()--",
  "Method": "Update",
  "Context": {
    "Source": "--Name-Table--"
  },
  "Params": {
    "Row": { ... },
    "Has": { ... }
  }
}
```

`Select` использует

```
{
  "ID": "--UUID4-value()--",
  "Method": "Select",
  "Context": {
    "Source": "--Name-Table--"
  },
  "Params": {
    "Has": { ... }
  }
}
```

Оффлайн @NovikovAntonY мы обсуждали параметр `Where` как наиболее подходящий. Но че-то я сегодня проснулся не с той ногой и, в общем...
Предлагаю использовать такой совсем простой параметр как `Has` в котором поведение совсем простое.

1. Все поля присутствующие в этом объекте объединяются оператором `AND`
2. Если хотя бы одно значение является массивом то значения этого массива объединяются оператором `OR`.

Надо вот понять насколько это будет тебе удобно чтобы вести поиск или фильтрацию?

**Comment by rianby64** [comment]
Я знаю, что повторяюсь поскольку уже существуют дофигищее всяких фремворков DB-ORMs но тем не менее, я собираюсь запрограммировать самое простое для нашего проекта. В общем. Жду комменты.

**Comment by NovikovAntonY** [comment]
@rianby64 в целом всё отлично, правда я не совсем могу понять зачем в `Select ` поле `Has`? Что мне туда передавать при открытии страницы? Может как-то связать это с пагинацией?

**Comment by rianby64** [comment]
Да! Именно. Это будет для поиска. Пагинацию оформим под другими параметрами. К примеру https://jsonapi.org/format/#fetching-pagination

**Comment by NovikovAntonY** [comment]
@rianby64 Отлично, так и сделаем)

**Comment by rianby64** [comment]
Мне опять не нравится название... `Has` вообще название ни о чём.
Кажется проще будет если этот параметр называть... `PK` что и понимается как "Primary-Key" или "Primary Keys". Фиг его знает...

**Comment by NovikovAntonY** [comment]
@rianby64 ну давай подумаем еще, насколько легко тебе поменять название? как по мне `primaryKeys`   было бы отлично, без сокращения

**Comment by rianby64** [comment]
Допустим:

1.

```json
{
  "Method": "Update",
  "Context": { ... },
  "Params": {
   "Row": {
      "Price": 100,
      "Description": "A new description"
    },
    "PrimaryKeys": {
      "ID": 1453
    }
  }
}
```

2.

```json
{
  "Method": "Update",
  "Context": { ... },
  "Params": {
   "Row": {
      "Price": 100,
      "Description": "A new description"
    },
    "PK": {
      "ID": 1453
    }
  }
}
```

3.

```json
{
  "Method": "Update",
  "Context": { ... },
  "Params": {
    "Row": {
      "Price": 100,
      "Description": "A new description"
    },
    "Keys": {
      "ID": 1453
    }
  }
}
```

4.

```json
{
  "Method": "Update",
  "Context": { ... },
  "Params": {
    "Row": {
      "Price": 100,
      "Description": "A new description"
    },
    "Where": {
      "ID": 1453
    }
  }
}
```

5.

```json
{
  "Method": "Update",
  "Context": { ... },
  "Params": {
    "Row": {
      "Price": 100,
      "Description": "A new description"
    },
    "Has": {
      "ID": 1453
    }
  }
}
```

**Comment by rianby64** [comment]
Хотелось бы понять какой из них самый прикольный.

`PrimaryKeys` мне нравится но не до конца. Если будет одно единственное поле `ID` то он уже не `PrimaryKeys` а `PrimaryKey`.

`Where` вообще дичь! так как он подсказывает, что под этим словом реализована вся логика работы со сложными условиями. А это не так.

`Has` кажется самый прикольный... Но жаль, что он ничего не говорит о работе с `Primary Keys`.

**Comment by rianby64** [comment]
Пока я оставляю как `PK`. Как придем к решению то просто переименуем.

**Comment by NovikovAntonY** [comment]
@rianby64 окей, получается с этим я могу уже работать?

**Comment by rianby64** [comment]
Все еще в процессе... думаю, что сегодня вечером будет уже полноценная версия со следующим поведением

```json
{
  "Method": "Insert",
  "Context": { ... },
  "Params": {
    "Row": {
      "Price": 100,
      "Description": "A new description"
    }
  }
}
```

```json
{
  "Method": "Update",
  "Context": { ... },
  "Params": {
    "Row": {
      "Price": 100,
      "Description": "A new description"
    },
    "PK": {
      "ID": 1453
    }
  }
}
```

```json
{
  "Method": "Delete",
  "Context": { ... },
  "Params": {
    "PK": {
      "ID": 1453
    }
  }
}
```

**Comment by NovikovAntonY** [comment]
@rianby64 Отлично, всё работает!
